"""
Chat Endpoint
Provides both standard JSON responses and streaming (SSE) responses
for the RAG-powered academic chatbot.
"""

import json
import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.schemas.models import ChatRequest, ChatResponse
from app.services.ai_logic import ai_logic_service
from app.services.vector_store import vector_store_service

logger = logging.getLogger(__name__)

router = APIRouter(tags=["Chat"])


@router.post(
    "/chat",
    response_model=ChatResponse,
    summary="Chat with Academic AI",
    description=(
        "Kirim pertanyaan akademik dan dapatkan jawaban berbasis dokumen. "
        "Jawaban dihasilkan menggunakan teknik RAG (Retrieval-Augmented Generation)."
    ),
)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Process a question through the RAG pipeline and return a full response.

    The pipeline:
    1. Retrieves relevant document chunks from ChromaDB
    2. Uses Llama 3.2 3B to generate an answer based on the context
    3. Returns the answer along with source documents
    """
    try:
        response = await ai_logic_service.get_answer(
            question=request.question,
            category=request.category.value if request.category else None,
        )
        return response
    except Exception as e:
        logger.error("Chat error: %s", e, exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Gagal memproses pertanyaan: {str(e)}",
        )


@router.post(
    "/chat/stream",
    summary="Chat with Streaming (SSE)",
    description=(
        "Kirim pertanyaan dan terima jawaban secara streaming (token per token) "
        "melalui Server-Sent Events untuk pengalaman real-time."
    ),
)
async def chat_stream(request: ChatRequest) -> StreamingResponse:
    """
    Stream the RAG answer token-by-token using Server-Sent Events (SSE).

    This endpoint is optimized for real-time UI rendering where each token
    is sent as soon as it's generated by the LLM.
    """

    async def event_generator():
        """Generate SSE events for each token."""
        try:
            # First, send source documents info
            retrieved_docs = vector_store_service.search_similar(
                query=request.question,
                category=request.category.value if request.category else None,
            )

            # Send sources as initial event (includes versioning metadata)
            sources_data = [
                {
                    "source": doc["source"],
                    "category": doc["category"],
                    "relevance_score": doc["relevance_score"],
                    "document_year": doc.get("document_year"),
                    "is_latest": doc.get("is_latest", True),
                    "ocr_used": doc.get("ocr_used", False),
                }
                for doc in retrieved_docs
            ]
            yield f"event: sources\ndata: {json.dumps(sources_data, ensure_ascii=False)}\n\n"

            # Stream answer tokens
            async for token in ai_logic_service.stream_answer(
                question=request.question,
                category=request.category.value if request.category else None,
            ):
                yield f"event: token\ndata: {json.dumps({'token': token}, ensure_ascii=False)}\n\n"

            # Send done event
            yield "event: done\ndata: {}\n\n"

        except Exception as e:
            logger.error("Streaming error: %s", e, exc_info=True)
            error_data = json.dumps({"error": str(e)}, ensure_ascii=False)
            yield f"event: error\ndata: {error_data}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
